# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import workspace_service_pb2 as workspace__service__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in workspace_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class WorkspaceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Empty = channel.unary_unary(
                '/workspace_service.WorkspaceService/Empty',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetUserWorkspaces = channel.unary_unary(
                '/workspace_service.WorkspaceService/GetUserWorkspaces',
                request_serializer=workspace__service__pb2.GetUserWorkspacesRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.GetUserWorkspacesResponse.FromString,
                _registered_method=True)
        self.GetWorkspace = channel.unary_unary(
                '/workspace_service.WorkspaceService/GetWorkspace',
                request_serializer=workspace__service__pb2.GetWorkspaceRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.GetWorkspaceResponse.FromString,
                _registered_method=True)
        self.GetWorkspaceWithUsers = channel.unary_unary(
                '/workspace_service.WorkspaceService/GetWorkspaceWithUsers',
                request_serializer=workspace__service__pb2.GetWorkspaceWithUsersRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.GetWorkspaceWithUsersResponse.FromString,
                _registered_method=True)
        self.GetAllWorkspaces = channel.unary_unary(
                '/workspace_service.WorkspaceService/GetAllWorkspaces',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=workspace__service__pb2.GetAllWorkspacesResponse.FromString,
                _registered_method=True)
        self.GetUserInWorkspace = channel.unary_unary(
                '/workspace_service.WorkspaceService/GetUserInWorkspace',
                request_serializer=workspace__service__pb2.GetUserInWorkspaceRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.UserMessage.FromString,
                _registered_method=True)
        self.CreateWorkspace = channel.unary_unary(
                '/workspace_service.WorkspaceService/CreateWorkspace',
                request_serializer=workspace__service__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.CreateWorkspaceResponse.FromString,
                _registered_method=True)
        self.PutUserToWorkspace = channel.unary_unary(
                '/workspace_service.WorkspaceService/PutUserToWorkspace',
                request_serializer=workspace__service__pb2.PutUserToWorkspaceRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.UserMessage.FromString,
                _registered_method=True)
        self.RemoveUserFromWorkspace = channel.unary_unary(
                '/workspace_service.WorkspaceService/RemoveUserFromWorkspace',
                request_serializer=workspace__service__pb2.RemoveUserFromWorkspaceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AddVisiblePlayersToUser = channel.unary_unary(
                '/workspace_service.WorkspaceService/AddVisiblePlayersToUser',
                request_serializer=workspace__service__pb2.AddVisiblePlayersToUserRequest.SerializeToString,
                response_deserializer=workspace__service__pb2.AddVisiblePlayersToUserResponse.FromString,
                _registered_method=True)
        self.RemoveVisiblePlayersFromUser = channel.unary_unary(
                '/workspace_service.WorkspaceService/RemoveVisiblePlayersFromUser',
                request_serializer=workspace__service__pb2.RemoveVisiblePlayersFromUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class WorkspaceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Empty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserWorkspaces(self, request, context):
        """GET

        Получить воркспейсы юзера 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspace(self, request, context):
        """Получить воркспейс без юзеров 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkspaceWithUsers(self, request, context):
        """Получить юзеров воркспейса 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllWorkspaces(self, request, context):
        """Получить все воркспейсы без юзеров 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserInWorkspace(self, request, context):
        """Получить состояние пользователя в воркспейсе 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWorkspace(self, request, context):
        """POST/PUT

        Создать воркспейс 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutUserToWorkspace(self, request, context):
        """Обновить состояние юзера в воркспейсе 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromWorkspace(self, request, context):
        """Удалить юзера из воркспейса 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddVisiblePlayersToUser(self, request, context):
        """Добавить видимых игроков пользователю в воркспейсе 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveVisiblePlayersFromUser(self, request, context):
        """Удалить видимых игроков пользователя в воркспейсе 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkspaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Empty': grpc.unary_unary_rpc_method_handler(
                    servicer.Empty,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUserWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserWorkspaces,
                    request_deserializer=workspace__service__pb2.GetUserWorkspacesRequest.FromString,
                    response_serializer=workspace__service__pb2.GetUserWorkspacesResponse.SerializeToString,
            ),
            'GetWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspace,
                    request_deserializer=workspace__service__pb2.GetWorkspaceRequest.FromString,
                    response_serializer=workspace__service__pb2.GetWorkspaceResponse.SerializeToString,
            ),
            'GetWorkspaceWithUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkspaceWithUsers,
                    request_deserializer=workspace__service__pb2.GetWorkspaceWithUsersRequest.FromString,
                    response_serializer=workspace__service__pb2.GetWorkspaceWithUsersResponse.SerializeToString,
            ),
            'GetAllWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllWorkspaces,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=workspace__service__pb2.GetAllWorkspacesResponse.SerializeToString,
            ),
            'GetUserInWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserInWorkspace,
                    request_deserializer=workspace__service__pb2.GetUserInWorkspaceRequest.FromString,
                    response_serializer=workspace__service__pb2.UserMessage.SerializeToString,
            ),
            'CreateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkspace,
                    request_deserializer=workspace__service__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=workspace__service__pb2.CreateWorkspaceResponse.SerializeToString,
            ),
            'PutUserToWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.PutUserToWorkspace,
                    request_deserializer=workspace__service__pb2.PutUserToWorkspaceRequest.FromString,
                    response_serializer=workspace__service__pb2.UserMessage.SerializeToString,
            ),
            'RemoveUserFromWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromWorkspace,
                    request_deserializer=workspace__service__pb2.RemoveUserFromWorkspaceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AddVisiblePlayersToUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddVisiblePlayersToUser,
                    request_deserializer=workspace__service__pb2.AddVisiblePlayersToUserRequest.FromString,
                    response_serializer=workspace__service__pb2.AddVisiblePlayersToUserResponse.SerializeToString,
            ),
            'RemoveVisiblePlayersFromUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveVisiblePlayersFromUser,
                    request_deserializer=workspace__service__pb2.RemoveVisiblePlayersFromUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workspace_service.WorkspaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workspace_service.WorkspaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkspaceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Empty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/Empty',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/GetUserWorkspaces',
            workspace__service__pb2.GetUserWorkspacesRequest.SerializeToString,
            workspace__service__pb2.GetUserWorkspacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/GetWorkspace',
            workspace__service__pb2.GetWorkspaceRequest.SerializeToString,
            workspace__service__pb2.GetWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkspaceWithUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/GetWorkspaceWithUsers',
            workspace__service__pb2.GetWorkspaceWithUsersRequest.SerializeToString,
            workspace__service__pb2.GetWorkspaceWithUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/GetAllWorkspaces',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            workspace__service__pb2.GetAllWorkspacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserInWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/GetUserInWorkspace',
            workspace__service__pb2.GetUserInWorkspaceRequest.SerializeToString,
            workspace__service__pb2.UserMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/CreateWorkspace',
            workspace__service__pb2.CreateWorkspaceRequest.SerializeToString,
            workspace__service__pb2.CreateWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutUserToWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/PutUserToWorkspace',
            workspace__service__pb2.PutUserToWorkspaceRequest.SerializeToString,
            workspace__service__pb2.UserMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUserFromWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/RemoveUserFromWorkspace',
            workspace__service__pb2.RemoveUserFromWorkspaceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddVisiblePlayersToUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/AddVisiblePlayersToUser',
            workspace__service__pb2.AddVisiblePlayersToUserRequest.SerializeToString,
            workspace__service__pb2.AddVisiblePlayersToUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveVisiblePlayersFromUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workspace_service.WorkspaceService/RemoveVisiblePlayersFromUser',
            workspace__service__pb2.RemoveVisiblePlayersFromUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
